flask_app/boba/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user

from ..forms import BobaReview, SearchForm, FriendSearchForm
from ..models import User, Review, BobaList, add_store
from ..utils import current_time

boba = Blueprint("boba", __name__)


""" ************ View functions ************ """


@boba.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()
    form2 = FriendSearchForm()
    return render_template("index.html", form=form, form2=form2)

@boba.route('/search', methods=['POST'])
def bsearch():
    search_form = SearchForm()
    friend_form = FriendSearchForm()

    if search_form.validate_on_submit():
        return redirect(url_for("boba.query_results", query=search_form.search_query.data))
    return render_template('index.html', form = search_form , form2=friend_form)


@boba.route('/friend_search', methods=['POST'])
def fsearch():
    search_form = SearchForm()
    friend_form = FriendSearchForm()

    if friend_form.validate_on_submit():
        return redirect(url_for("boba.query_friend_results", query=friend_form.friend_search_query.data))
    return render_template('index.html', form = search_form , form2=friend_form)


@boba.route("/search-results/<query>", methods=["GET"])
def query_results(query):
    add_store(query, "1399 New York Ave NW, Washington, DC 20005")
    results = BobaList.objects(name=query)
    return render_template("query.html", results=results, )

@boba.route("/search-friend-results/<query>", methods=["GET"])
def query_friend_results(query):
    results = User.objects(username=query)
    return render_template("friendquery.html", results=results)


@boba.route("/boba/<boba_id>", methods=["GET", "POST"])
def boba_detail(boba_id):

    result = BobaList.objects.get(boba_id=boba_id)
    form = BobaReview()
    if form.validate_on_submit() and current_user.is_authenticated:
        review = Review(
            commenter=current_user._get_current_object(),
            content=form.text.data,
            date=current_time(),
            boba_name=result.name,
            boba_id = result.boba_id,
        )
        review.save()
        current_user._get_current_object().modify(points= current_user._get_current_object().points + 50)
        current_user._get_current_object().save()
        return redirect(request.path)

    reviews = Review.objects(boba_id=boba_id)
    print(result.name)
    return render_template(
        "boba_detail.html", form=form, boba=result, reviews=reviews
    )


@boba.route("/user/<username>")
def user_detail(username):
    user = User.objects(username=username).first()
    reviews = Review.objects(commenter=user)

    return render_template("user_detail.html", username=username, reviews=reviews)

@boba.route("/about")
def about():
    return render_template("about.html")

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user

from .. import bcrypt
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm
from ..models import User

users = Blueprint("users", __name__)

""" ************ User Management views ************ """


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("boba.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed, points=0)
        user.save()

        return redirect(url_for("users.login"))

    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("boba.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("users.account"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("users.login"))

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("boba.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    username_form = UpdateUsernameForm()

    if username_form.validate_on_submit():
        current_user.modify(username=username_form.username.data)
        current_user.save()
        return redirect(url_for("users.account"))

    return render_template(
        "account.html",
        title="Account",
        username_form=username_form,
    )

flask_app/templates/about.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <p>Katie Spiegel</p>
    <p>Bubble tea has become very popular with a dedicated customer base. A website aside from yelp and google reviews will give bubble tea fans a place to go for solely bubble tea reviews and store locations. Being able to write and read reviews from other bubble tea fans will give that feedback credibility. Store owners will also be able to interact with their community and get direct feedback. Menus will also be more accessible, since a lot of the times bubble tea store websites are difficult to navigate. The website will be simple and clean, with pictures of the stores and items on their menus. 
    </p>
    <p></p>
    <p>I was short on time and wish I could have made the site prettier, as it obviously is bare bones. </p>
    <p>The idea does have much potential though and I may look into creating a better product later on.</p>
    <p>Thank you for helping me on such short notice multiple times this semester! Have a great summer.</p>
</div>


{% endblock %}

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h1>welcome {{ current_user.username }}!</h1>
        <h2>you have {{ current_user.points }} points</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ username_form.csrf_token }}
            <div class="form-group">
                {{ username_form.username.label(class="form-control-label") }}
                {{ username_form.username(class="form-control form-control-lg") }}

                {% if username_form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in username_form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ username_form.submit }}
            </div>
        </form>
    </div>
</div>
<a href="{{ url_for('boba.user_detail', username=current_user.username) }}">
    <h4>Click here to see all of your posts and comments!</h4>
</a>
{% endblock %}>

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>boba reviews</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/boba_detail.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<b>{{ error_msg }}</b>
{% endif %}
{# Display card for the movie details #}
<div class="row">
  <div class="col">
    <div class="card text-center">
      <div class="card-header">
        how was {{ boba.name }} ?
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><b>address:</b> {{ boba.address }} </li>
        </ul>
      </div>
    </div>
  </div>
</div>
{# Reviews #}
<div class="row">
  <div class="col-md-12">
    <h1> Reviews <small class="float-right">{{ reviews|length }} reviews</small></h1>
    <ul class="media-list">
      {% for review in reviews %}
      <li class="media review-item">
        <div class="media-body">
          <span class="float-right">
            <small>{{ review.date }}</small>
          </span>
          <a href="{{ url_for('boba.user_detail', username=review.commenter.username) }}">
            <strong>@{{ review.commenter.username }}</strong>
          </a>
          <p>
            {{ review.content }}
          </p>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% if current_user.is_authenticated %}
<div class="row">
  <div class="col">
    <form method="POST" action="">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.text.label }}
        {{ form.text(class="form-control") }}

        {% if form.text.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.text.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

      </div>
      {{ form.submit() }}
    </form>
  </div>
</div>
{% endif %}
{% endblock content %}

flask_app/templates/friendquery.html
{% extends "header.html" %}
{% block content %}
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

<div class="container-fluid">
    {% for result in results %}
    <div class="media">
        <div class="media-body">
            <h5 class="mt-0"><a href="{{ url_for('boba.user_detail', username=result.username) }}">{{ result.username }}</a></h5>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('boba.index') }}">boba review</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('boba.about') }}">
                    About
                </a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">
                    Register
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col">
        <form action="{{ url_for('boba.bsearch') }}" class="form-inline my-2 my-lg-0" method="POST">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {{ form.csrf_token }}
            {{ form.search_query(class="form-control", placeholder="search") }}

            {% if form.search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.search_query.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            {{ form.submit(class="btn btn-outline-success") }}
        </form>
    </div>
    <div class="col">
        <h2>search for boba places in your area to review! try gong cha or jumbo jumbo</h2>
    </div>
</div>
<div class = "row">
    <div class="col">
        <form action="{{ url_for('boba.fsearch') }}" class="form-inline my-2 my-lg-0" method="POST">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {{ form2.csrf_token }}
            {{ form2.friend_search_query(class="form-control", placeholder="search") }}

            {% if form2.friend_search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form2.friend_search_query.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            {{ form2.submit(class="btn btn-outline-success") }}
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Log In</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you <b>don't</b> have an account, then <a href="{{ url_for('users.register') }}">Register!</a>
    </div>
</div>
<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label green-text") }}
                {{ form.username(class="form-control form-control-md") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}

                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/query.html
{% extends "header.html" %}
{% block content %}
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

<div class="container-fluid">
    {% for result in results %}
    <div class="media">
        <div class="media-body">
            <h5 class="mt-0"><a href="{{ url_for('boba.boba_detail', boba_id=result.boba_id) }}">{{ result.name }} {{ result.boba_id }}</a></h5>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Registration</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you already have an account, then just <a href="{{ url_for('users.login') }}">Log In!</a>
    </div>
</div>
<!-- Registration Form: -->
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-lg") }}
                {% if form.email.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% if form.confirm_password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

flask_app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <img class="propic" src="data:image/png;base64,{{image}}" alt="image">
    </div>
    <div class="col">
        <h2>{{ username }}'s account</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        <h1> reviews <small class="float-right">{{ reviews.count() }} reviews</small></h1>
        <ul class="media-list">
            {% for review in reviews %}
            <li class="media review-item">
                <div class="media-body">
                    <span class="float-right">
                        <small>{{ review.date }}</small>
                    </span>
                    <strong>For: <a href="{{ url_for('boba.boba_detail', boba_id=review.boba_id) }}">
                            {{ review.boba_name }}
                        </a>
                    </strong>
                    <p>
                        {{ review.content }}
                    </p>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}